name: emotion-clf-pipeline
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python>=3.11,<3.12
  - pip

  # PyTorch related (from torch = "*", torchvision = "*", torchaudio = "*")
  - pytorch
  - torchvision
  - torchaudio

  # Core ML, data handling, and utilities
  - transformers>=4.51.3 # from ^4.51.3
  - pandas>=2.2.3 # from ^2.2.3
  - scikit-learn>=1.6.1 # from ^1.6.1
  - tqdm>=4.67.1 # from ^4.67.1
  - nltk>=3.9.1 # from ^3.9.1
  - seaborn>=0.13.2 # from ^0.13.2
  - openpyxl>=3.1.5 # from ^3.1.5
  - jupyter>=1.1.1 # from ^1.1.1
  - ipykernel>=6.29.5 # from ^6.29.5
  - fastapi>=0.115.12 # from ^0.115.12
  - textblob>=0.19.0 # from ^0.19.0
  - black>=25.1.0 # from ^25.1.0
  - isort>=6.0.1 # from ^6.0.1
  - pytest>=8.3.5 # from ^8.3.5
  - protobuf>=6.31.0 # from ^6.31.0
  - sentencepiece>=0.2.0 # from ^0.2.0
  - tabulate>=0.9.0 # from ^0.9.0
  - termcolor>=3.1.0 # from ^3.1.0
  - python-dotenv>=1.0.0 # from ^1.0.0

  # Documentation
  - sphinx>=8.2.3 # from ^8.2.3
  - sphinx-rtd-theme>=3.0.2 # from ^3.0.2

  # MLOps and Azure
  - mlflow>=2.22.0 # from ^2.22.0
  - azure-identity>=1.23.0 # from ^1.23.0

  # Development dependencies (from tool.poetry.group.dev.dependencies)
  - flake8==5.0.4 # from flake8 = "5.0.4"
  - importlib-metadata>=8.2.0 # from ^8.2.0
  - pre-commit>=4.2.0 # from ^4.2.0

  # Pip-installed packages
  - pip:
    - assemblyai>=0.40.2 # from ^0.40.2
    - sentence-transformers>=4.1.0 # from ^4.1.0
    - uvicorn[standard]>=0.34.2 # from uvicorn = {extras = ["standard"], version = "^0.34.2"}
    - pytubefix>=8.13.1 # from ^8.13.1
    - git+https://github.com/openai/whisper.git#egg=openai-whisper # from openai-whisper = {git = "..."}
    - sphinx-autobuild>=2024.10.3 # from ^2024.10.3
    - azure-ai-ml>=1.27.1 # from ^1.27.1
