global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API metrics
  - job_name: 'emotion-backend'
    static_configs:
      - targets: ['backend:3120']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Container metrics for resource monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Custom ML metrics from API
  - job_name: 'emotion-ml-metrics'
    static_configs:
      - targets: ['backend:3120']
    metrics_path: '/metrics'
    scrape_interval: 10s
