global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API metrics
  - job_name: 'emotion-backend'
    static_configs:
      - targets: ['backend:80']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Custom ML metrics exporter
  - job_name: 'ml-metrics'
    static_configs:
      - targets: ['backend:8000']  # We'll add this endpoint
    metrics_path: '/ml-metrics'
    scrape_interval: 30s
